First commit
GoogleCloudPlatform/blueprints pull request #1
Opened 2021-04-23 16:46 UTC by markebalch

Two sample blueprints for BC.  LMK if any issues.

2021-04-23 17:05 UTC, morgante requested changes

2021-04-23 17:05 UTC, morgante commented on quick-start/README.md
> +# Blueprints quick-start
I'm not sure we should nest these under a "quick-start" section.

2021-04-23 17:05 UTC, morgante commented on quick-start/bucket/Kptfile
> +  name: bucket-demo
Blueprint name should match directory name (`bucket`) and generally we should avoid "demo" blueprints.

2021-04-23 17:05 UTC, morgante commented on quick-start/bucket/Kptfile
> +
Please remove superfluous whitespace between lines.

2021-04-23 17:05 UTC, morgante commented on quick-start/bucket/Kptfile
> +      x-k8s-cli:
This should be a required setter.

2021-04-23 17:05 UTC, morgante commented on quick-start/bucket/Kptfile
> +      x-k8s-cli:
This should be a required setter.

2021-04-23 17:05 UTC, morgante commented on quick-start/data-demo/Kptfile
> +  name: data-demo
How does data-demo differ from bucket demo / what's the purpose of this blueprint? We should have a README for all blueprints.

2021-04-27 15:59 UTC, markebalch commented
Changes made

2021-04-27 19:16 UTC, morgante approved these changes

2021-04-27 19:17 UTC, merged