feat: Initial version of the Namespace blueprint
GoogleCloudPlatform/blueprints pull request #84
Opened 2021-11-03 01:30 UTC by kaariger

The Namespace blueprint allows users to create Kubernetes namespaces in GKE clusters via ACM.

- Create the namespace
- Create a Role Binding for ClusterRole admin to an specified email group
- Create a repo-sync object to sync resources from a Namespace repository via ACM

2021-11-03 01:48 UTC, kaariger commented
Todo:
- [ ] Fix the issue with repo-sync error related to repo access

2021-11-03 03:58 UTC, kaariger commented
/test all

2021-11-03 04:11 UTC, kaariger commented
/test all

2021-11-05 21:13 UTC, bharathkkb requested changes

2023-02-24 23:02 UTC, closed without merging